language: python
python:
- 2.7
- 3.6
- 3.7
env:
- SA_VERSION=1.0.19
- SA_VERSION=1.1.18
- SA_VERSION=1.2.19
- SA_VERSION=1.3.8
cache:
  directories:
  - "$HOME/.cache/pip"
  - "$HOME/.pyenv"
install:
- make clean install
- pip install SQLAlchemy==$SA_VERSION
script:
- make lint tests
deploy:
  provider: pypi
  user: akshayn
  password:
    secure: kswfuu9EL2O1ZhdPQS3fQ0vvy4YKpIXbeNH6n7dlssS0hRe54pjlIR95lReRGzHtS0Vhx2/NJjlsPAI0MgwKAcUHsYfxS7tPut2haZkjKlMae0u2QD6wv7eW9nY9xEHUJ91dR+5aVxD+OzkhEvBfMCYPoMZ9XMYCpGxwYekRk6U6UVWID2KQGzv3Pdh9a9LPgvYdWzuHUdUwG/JUIXwrfThqbnNV4Oc9sM3ISAJNbwWb/ltD7zpHyBGSuSgayTqNcQCEKG2gZ/f86omF/M08lpBs3rVJEYlGkvGBcgcpbUVood4hA/DMpdlw0RSpirXMgJkEptpt29LWk0sJ6uhFwmN3n1NNv1Qeec2IHU9BTg+lmT9zHJHer2GoOk7TbPbLSbgKPjQB0E9XZ9YplkCS/0ZWl2GYPQ0CQycs51sn7/xapfbP/7iIEVCEddmvMY6Kd43dLP7YEq8D22nDB1c73LQfLumGb5/6/X6BHY+hKpZF5usUVw0SvKAk7YC00Cv8EtAKLnFy+SIQy4EDEHvtx6wf4TfSz9Kvv40Avr1VAInqPLF3KqQvf/oqaHmESqxWQCptVGOq8cPD1+q30raVsmUcCdhkuIebLMTNo9fVk3Lm7neuC5cFHwL5xE3PV3blgQk4Rv+CAQu7WJbID9NLqYTQa4Ue/Qqdey7flSgGhv8=
  on:
    python: 3.7
    condition: "$SA_VERSION = 1.3.8"
    tags: true
    distributions: sdist bdist_wheel
    repo: NerdWalletOSS/versionalchemy
